<?php
    $stUkoly = $db->prepare("SELECT * FROM task_type");
    $stUkoly->execute();
    $ukoly = $stUkoly->get_result();
    
    
    $stUzivatel = $db->prepare("SELECT * FROM users");
    $stUzivatel->execute();
    $uzivatele = $stUzivatel->get_result();

    $stMazlicci = $db->prepare("SELECT * FROM animals");
    $stMazlicci->execute();
    $mazlicci = $stMazlicci->get_result();

    $stFamily = $db->prepare("SELECT * FROM family");
    $stFamily->execute();
    $rodina = $stFamily->get_result();

    ?>
<?php if($uzivatel['role_id'] === 1 || $uzivatel['role_id'] === 2){ ?>
<h1>Vytvoření nového úkolu</h1>
<div class="task-create-form">

<form method="POST">
    <div class="task-input">
    <label for="task_type">Typ úkolu</label>

    <select name="task_type" id="task_type">

        <?php
        foreach($ukoly as $ukol){
        ?>
            <option value="<?= $ukol['id'] ?>">
                <?= htmlspecialchars($ukol['name']) ?>
            </option>
        <?php
        }
        ?>

    </select>
    </div>
    <div class="task-input">
    <label for="user_id">Člen</label>
    <select name="user_id" id="">
        <?php
        foreach($uzivatele as $uzivatel){
        ?>
        <option value="<?= $uzivatel['id']?>">
            <?= htmlspecialchars($uzivatel['username'])?>
        </option>
        <?php
        }
        ?>
    </select>
    </div>
    <div class="task-input">
    <label for="animal_id">Člen</label>
    <select name="animal_id" id="">
        <?php
        foreach($mazlicci as $mazlicek){
        ?>
        <option value="<?= $mazlicek['id']?>">
            <?= htmlspecialchars($mazlicek['name'])?>
        </option>
        <?php
        }
        ?>
    </select>
    </div>
    <div class="task-input">
    <label for="family_id">Člen</label>
    <select name="family_id" id="">
        <?php
        foreach($rodina as $rodinaS){
        ?>
        <option value="<?= $rodinaS['ID']?>">
            <?= htmlspecialchars($rodinaS['family_name'])?>
        </option>
        <?php
        }
        ?>
    </select>
    </div>

    <div class="task-input">
    <label for="datum_splneni">Datum splnění</label>
        <input type="date" name="datum_splneni">
    </div>

    <div class="task-input">
        <label for="descpription">Popisek </label>
        <textarea name="description" id=""></textarea>
    </div>
    <button name="ulozTask">    
        Uložit
    </button>

</form>
</div>

<?php } ?>