<body>
    <div class="login-page-wrapper">
<div class="login-box">
        <h1>Přihlášení</h1>

        <?php if ($chyba) echo "<span class='error-msg'>Chybné přihlašovací údaje!</span>"; ?>
        
        <form method="post">
            <label>Username: <input type="text" name="username" required></label>
            <label>Password: <input type="password" name="password" required></label>
            <input type="submit" value="Přihlásit se">
        </form>
    </div>
</div>

