<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Přihlášení</title>
</head>
<body>
    <h1>Přihlášení</h1>

    <?php if ($chyba) echo "<b>Chybné přihlašovací údaje!</b><br>"; ?>
    
    <form method="post">
        <label>Username: <input type="text" name="username" required></label><br>
        <label>Password: <input type="password" name="password" required></label><br>
        <input type="submit" value="Přihlásit se">
    </form>

</body>
</html>
</div>

