<?php
    $stUkoly = $db->prepare("SELECT * FROM task_type");
    $stUkoly->execute();
    $ukoly = $stUkoly->get_result();    
    ?>
<form method="POST">

    <label for="task_type">Typ úkolu</label>

    <select name="task_type" id="task_type">

        <?php
        foreach($ukoly as $ukol){
        ?>
            <option value="<?= $ukol['id'] ?>">
                <?= htmlspecialchars($ukol['name']) ?>
            </option>
        <?php
        }
        ?>

    </select>

    <button type="submit">
        Uložit
    </button>

</form>