<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    <title>Pet Scheduler</title>
</head>
    <body>
        <nav class="navbar">
        <a href="#" class="logo">Pet Scheduler</a>
        <ul class="nav-links">
            <li><a href="#">Domů</a></li>
            <li><a href="#">O nás</a></li>
            <li><a href="./login.phtml">Přihlášení</a></li>
            <li><a href="#">Kontakt</a></li>
        </ul>
    </nav>
 