<!DOCTYPE html>
<html lang="cs">

<head>

    <meta charset="UTF-8">

    <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0"
    >

    <title>Pet Scheduler</title>

    <link
        rel="stylesheet"
        href="./style.css"
    >

</head>

<body>

<div class="app-layout">

    <!-- SIDEBAR -->

    <aside class="sidebar">

        <div class="sidebar-logo">
            <img src="./imgs/logo.png" width="120px" height="40px" alt="">
        </div>

        <nav class="sidebar-menu">

            <a href="./dashboard.php" class="sidebar-link ">
                🏠 Dashboard
            </a>

            <a href="./family.php" class="sidebar-link">
                👨‍👩‍👧 Rodina
            </a>

            <a href="./pets.php" class="sidebar-link">
                🐶 Mazlíčci
            </a>

            <a href="./tasks.php" class="sidebar-link">
                ✅ Úkoly
            </a>

        </nav>

    </aside>

    <!-- PRAVÁ ČÁST -->

    <div class="main-area">

        <!-- TOPBAR -->

        <header class="topbar">

            <details class="user-dropdown">

                <summary class="dropdown-toggle">

                    <div class="user-profile">

                        <svg xmlns="http://www.w3.org/2000/svg"
                             width="18"
                             height="18"
                             viewBox="0 0 24 24"
                             fill="none"
                             stroke="currentColor"
                             stroke-width="2"
                             stroke-linecap="round"
                             stroke-linejoin="round">

                            <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path>

                            <circle cx="12" cy="7" r="4"></circle>

                        </svg>

                        <span class="user-name">

                            <?php
                                echo htmlspecialchars(
                                    $uzivatel['username']
                                    ?? 'Uživatel'
                                );
                            ?>

                        </span>

                    </div>

                </summary>

                <div class="dropdown-menu">

                    <a
                        href="./logout.php"
                        class="dropdown-item"
                    >
                        Odhlásit se
                    </a>

                </div>

            </details>

        </header>

        <!-- CONTENT -->

        <main class="content">
