<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./style.css">
    <title>Pet Scheduler</title>
</head>
    <body>
        <nav class="navbar">
        <img src="./imgs/logo.png" alt="Mazlíček logo">
        <a href="index.php" class="logo">Pet Scheduler</a>
        <ul class="nav-links">
            <li><a href="./login.php">Přihlášení</a></li>
        </ul>
    </nav>
 